/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/**************************************************************************************************************
 *  INCLUDES
 **************************************************************************************************************/
#include <stdint.h>
#include "Std_Types.h"
#include "RCC_Interface.h"
#include "GPIO_Interface.h"
#include "STK_Interface.h"
#include "SPI_Interface.h"
#include "N5110_Interface.h"

/**********************************************************************************************************
*  LOCAL MACROS CONSTANT\FUNCTION
***********************************************************************************************************/
#define spi1	1
#define spi2	2
/************************************************************************************************************
 *  LOCAL DATA
 ************************************************************************************************************/

/************************************************************************************************************
 *  GLOBAL DATA
 ***********************************************************************************************************/

/************************************************************************************************************
 *  LOCAL FUNCTION PROTOTYPES
 ***********************************************************************************************************/

/*************************************************************************************************************
 *  LOCAL FUNCTIONS
 ************************************************************************************************************/

/*************************************************************************************************************
 *  GLOBAL FUNCTIONS
 ************************************************************************************************************/


/******************************************************************************
* \Syntax          : Std_ReturnType FunctionName(AnyType parameterName)
* \Description     : Describe this service
*
* \Sync\Async      : Synchronous
* \Reentrancy      : Non Reentrant
* \Parameters (in) : parameterName   Parameter Describtion
* \Parameters (out): None
* \Return value:   : Std_ReturnType  E_OK
*                                    E_NOT_OK
*******************************************************************************/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
Pin setup

	SPI - 1
	-->
	PA0 --> RST
	PA1 --> DC
	PA2 --> Screen Light
	PA4 --> SS
	PA5 --> SCLK
	PA7 --> MOSI

	3.3V --> Vcc
	G --> Grd
*/

int main(void)
{
	/*initialization*/
	/* System clock initialization */
	RCC_voidSysClockInit();
	/* GPIO Peripheral clock initialization */
	RCC_voidEnablePerClk(RCC_APB2, RCC_GPIOA);
	//RCC_voidEnablePerClk(RCC_APB2, RCC_SPI1);
	STK_voidInit();
	n5110_init(spi1);
	n5110_clear();
	n5110_light(GPIO_LOW);

    /* Loop forever */
	for(;;)
	{
		n5110_print(5, 5, "HELLO WORLD");
		//n5110_light(GPIO_LOW);
		STK_DelayMs(2000000);
		n5110_clear();
		//n5110_light(GPIO_HIGH);
		STK_DelayMs(2000000);
	}//End of Infinite for loop
}
/************************************************************************************************************
 *  END OF FILE: main.c
 ************************************************************************************************************/
