/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/
#include "Std_Types.h"
#include "RCC_Interface.h"


int main(void)
{

	/*		System Clock initialization		*/
	RCC_voidSysClockInit();

	/*		RCC Per En		== GOIA		*/
	RCC_voidEnablePerClk(RCC_APB2, RCC_GPIOA);

	/* Loop forever */
	for(;;);
}
