/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Std_Types.h"
#include "RCC_Interface.h"
#include "GPIO_Interface.h"

void Delay_1Sec()
{
	for(int i = 0 ; i < 100000 ; i++)
	{
		asm("NOP");
	}
}
//uint8 InPin = 0;
int main(void)
{

	/*	RCC Init						*/
	RCC_voidSysClockInit();

	/*	RCC for Peripheral		GPIOA		*/
	RCC_voidEnablePerClk(RCC_APB2, RCC_GPIOA);

	/*	RCC for Peripheral		GPIOB		*/
	RCC_voidEnablePerClk(RCC_APB2, RCC_GPIOB);

	/*	RCC for Peripheral		GPIOC		*/
	RCC_voidEnablePerClk(RCC_APB2, RCC_GPIOC);

	/*	GPIO Direction						*/
	GPIO_voidSetPinDirection(GPIO_PORTB, GPIO_PIN4, GPIO_INPUT_PULL);
	//GPIO_voidSetPinValue(GPIO_PORTA,GPIO_PIN0 , GPIO_HIGH);
	//GPIO_voidSetPinDirection(GPIO_PORTB, GPIO_PIN0, GPIO_OUTPUT_10_PP);
	GPIO_voidSetPinDirection(GPIO_PORTC, GPIO_PIN13, GPIO_OUTPUT_50_PP);

	uint8 InPin = 0;

    /* Loop forever */
	for(;;)
	{
		GPIO_voidGetPinValue(GPIO_PORTB, GPIO_PIN4, &InPin);
		if(InPin == 0)
		{
			GPIO_voidSetPinValue(GPIO_PORTA, GPIO_PIN0, GPIO_HIGH);
			//GPIO_voidSetPinValue(GPIO_PORTB, GPIO_PIN0, GPIO_HIGH);
			GPIO_voidSetPinValue(GPIO_PORTC, GPIO_PIN13, GPIO_LOW);
		}
		else
		{
			GPIO_voidSetPinValue(GPIO_PORTA, GPIO_PIN0, GPIO_LOW);
			GPIO_voidSetPinValue(GPIO_PORTC, GPIO_PIN13, GPIO_HIGH);
		}

//		Delay_1Sec();
////		GPIO_voidSetPinValue(GPIO_PORTA, GPIO_PIN0, GPIO_LOW);
//		GPIO_voidSetPinValue(GPIO_PORTB, GPIO_PIN0, GPIO_LOW);
//		GPIO_voidSetPinValue(GPIO_PORTC, GPIO_PIN13, GPIO_HIGH);
//		Delay_1Sec();

	}
}
