/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "Std_Types.h"
#include "RCC_Interface.h"
#include "GPIO_Interface.h"
#include "NVIC_Interface.h"
#include "STK_Interface.h"



void Flash_voidLED(void)
{
	GPIO_voidSetPinValue(GPIO_PORTC, GPIO_PIN13, GPIO_HIGH);
	STK_voidBusyWait(1000000);
	GPIO_voidSetPinValue(GPIO_PORTC, GPIO_PIN13, GPIO_LOW);
	STK_voidBusyWait(1000000);
}

int main(void)
{
	/*	RCC Init						*/
		RCC_voidSysClockInit();

		/*	RCC for Peripheral		GPIOA		*/
		RCC_voidEnablePerClk(RCC_APB2, 2);

		/*	RCC for Peripheral		GPIOB		*/
		RCC_voidEnablePerClk(RCC_APB2, 3);

		/*	RCC for Peripheral		GPIOC		*/
		RCC_voidEnablePerClk(RCC_APB2, 4);

		/*	GPIO Direction						*/
		GPIO_voidSetPinDirection(GPIO_PORTA, GPIO_PIN0, GPIO_INPUT_PULL);
		GPIO_voidSetPinValue(GPIO_PORTA,GPIO_PIN0 , GPIO_HIGH);

		GPIO_voidSetPinDirection(GPIO_PORTB, GPIO_PIN0, GPIO_OUTPUT_10_PP);
		GPIO_voidSetPinDirection(GPIO_PORTC, GPIO_PIN13, GPIO_OUTPUT_50_PP);

		/*		Initialize System Tick	*/
		STK_voidInit();
//		STK_voidSetPeriodicInterval(1000000, Flash_voidLED);
		STK_voidSetSingleInterval(1000000, Flash_voidLED);

    /* Loop forever */
	for(;;)
	{
/*		GPIO_voidSetPinValue(GPIO_PORTC, GPIO_PIN13, GPIO_HIGH);
		STK_voidBusyWait(1000000);
		GPIO_voidSetPinValue(GPIO_PORTC, GPIO_PIN13, GPIO_LOW);
		STK_voidBusyWait(1000000);*/


	}
}


